### ISSUE TITLE
[mobile] Страница form: лишнее предложение в инфо

### ISSUE THREAD

**Issue by alexbaumgertner** [up-htmlacademy/26591-pink#22]
@gimmortal 
![screenshot at oct 27 00-17-05](https://cloud.githubusercontent.com/assets/223620/10742807/27983d46-7c40-11e5-926a-d71643e8660d.png)

**Comment by gimmortal** [comment]
Думаю в шаблоне ошибка дизайнер торопился и не полностью отобразил текст, этот текст есть в текстовом слое photoshop

**Comment by alexbaumgertner** [comment]
А, тогда ок. Текст кажется к месту по смыслу.
